management:
  auditevents:
    enabled: true
  server:
    port: 8090
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    enabled: true
server:
  error:
    include-message: always
spring:
  main:
    banner-mode: "off"
  application:
    name: testApp
  profiles:
    active: local

test-props:
  datagroups:
    data:
      read:
        code: READ_DATA
        urlPattern:
          - /some/pattern/